# Site settings
title: Doeun Kim
email: doeun2@ucla.edu
description: >
 Department of Political Science
 4289 Bunche Hall
 Los Angeles, CA somewhere
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://do-eunkim.github.io" # the base hostname & protocol for your site
github_username:  do-eunkim
encoding: UTF-8
# Build settings
markdown: kramdown
